version: "3.9"

services:
  loadbalancer:
    image: lb-image       
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "2703:2703"      
    volumes:
      - ./config.json:/app/config.json   
