name: "ci-pipeline"

on:
  pull_request:
    branches:
      - "*"
  
  push:
    branches:
      - "main"

jobs:
  check-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v6 

      - name: Setup environment
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.22"
      
      - name: Check go version
        run: go version
        
  run-linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: actions/setup-go@v6

      - name: Setup Linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.3
          
  build-app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: actions/setup-go@v6
      
      - name: Build app
        run: go build